version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./etc/nginx/log/:/var/log/nginx/"
      - "./web/:/var/www/html/"
    ports:
      - "8080:80"
      - "61600-61900:61600-61900"
    depends_on:
      - php
      - mysql
      - redis

  php:
    build:
      context: .
    volumes:
      - "./web/:/var/www/html/"
    ports:
      - "9000:9000"
    
  mysql:
    image: mysql:8.0.33
    # image: mysql:5.7
    volumes:
      - "./etc/mysql/data/:/var/lib/mysql"
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"